// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeTkG9y_J4f_eAw9f-s2mtfCWYbIAPK2w',
    appId: '1:609160171719:web:d0c37479729a30190a6ee2',
    messagingSenderId: '609160171719',
    projectId: 'money-7eb69',
    authDomain: 'money-7eb69.firebaseapp.com',
    storageBucket: 'money-7eb69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLwZWY-bInx67cfVdcuUYAkiYR6khaQI',
    appId: '1:609160171719:android:d1fc55dcb304a7bb0a6ee2',
    messagingSenderId: '609160171719',
    projectId: 'money-7eb69',
    storageBucket: 'money-7eb69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcEvyy4lhjs9c_fgKhzhxLUsVWCiDeNpc',
    appId: '1:609160171719:ios:12a0345c16736da30a6ee2',
    messagingSenderId: '609160171719',
    projectId: 'money-7eb69',
    storageBucket: 'money-7eb69.firebasestorage.app',
    iosClientId: '609160171719-93hepmmchsd4ms9l1vdbu4crgshai8pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcEvyy4lhjs9c_fgKhzhxLUsVWCiDeNpc',
    appId: '1:609160171719:ios:12a0345c16736da30a6ee2',
    messagingSenderId: '609160171719',
    projectId: 'money-7eb69',
    storageBucket: 'money-7eb69.firebasestorage.app',
    iosClientId: '609160171719-93hepmmchsd4ms9l1vdbu4crgshai8pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeTkG9y_J4f_eAw9f-s2mtfCWYbIAPK2w',
    appId: '1:609160171719:web:94b3aaa40939d38d0a6ee2',
    messagingSenderId: '609160171719',
    projectId: 'money-7eb69',
    authDomain: 'money-7eb69.firebaseapp.com',
    storageBucket: 'money-7eb69.firebasestorage.app',
  );
}
